#pragma once

#include "RefStep0ShapeBridge.h"

namespace aecct_ref {
namespace ref_v3 {

enum : int {
  REFV3_LAYER0_ID = 0,
  REFV3_LAYER1_ID = 1,
  REFV3_TOKENS_T = ModelShapes::T_TOKENS,
  REFV3_D_MODEL = ModelShapes::D_MODEL,
  REFV3_HEADS = ModelShapes::N_HEADS,
  REFV3_D_HEAD = ModelShapes::D_HEAD,
  REFV3_FF_DIM = ModelShapes::D_FFN,
  REFV3_VAR_N = ModelShapes::N_VARS,
  REFV3_ATTN_MATRIX_ELEMS = ModelShapes::T_TOKENS * ModelShapes::D_MODEL
};

#ifndef REFV3_CATAPULT_MODE
#define REFV3_CATAPULT_MODE 0
#endif

#if REFV3_CATAPULT_MODE
#ifndef REFV3_SYNTH_ONLY
#define REFV3_SYNTH_ONLY 1
#endif
#endif

#ifndef REFV3_HAS_MC_SCVERIFY_HEADER
#if defined(__has_include)
#if __has_include(<mc_scverify.h>)
#define REFV3_HAS_MC_SCVERIFY_HEADER 1
#else
#define REFV3_HAS_MC_SCVERIFY_HEADER 0
#endif
#else
#define REFV3_HAS_MC_SCVERIFY_HEADER 0
#endif
#endif

#ifndef REFV3_LN_INV_MODE_PURE_LUT
#define REFV3_LN_INV_MODE_PURE_LUT 0
#endif
#ifndef REFV3_LN_INV_MODE_LUT_NR1
#define REFV3_LN_INV_MODE_LUT_NR1 1
#endif

#ifndef REFV3_LN_INV_MODE
#ifdef REFV3_LN_INV_SQRT_SYNTH_POLICY
#define REFV3_LN_INV_MODE REFV3_LN_INV_SQRT_SYNTH_POLICY
#else
#define REFV3_LN_INV_MODE REFV3_LN_INV_MODE_PURE_LUT
#endif
#endif

#ifndef REFV3_LN_INV_SQRT_SYNTH_LUT_ONLY
#define REFV3_LN_INV_SQRT_SYNTH_LUT_ONLY REFV3_LN_INV_MODE_PURE_LUT
#endif
#ifndef REFV3_LN_INV_SQRT_SYNTH_LUT_PLUS_NR1
#define REFV3_LN_INV_SQRT_SYNTH_LUT_PLUS_NR1 REFV3_LN_INV_MODE_LUT_NR1
#endif

#ifndef REFV3_LN_INV_SQRT_SYNTH_POLICY
#define REFV3_LN_INV_SQRT_SYNTH_POLICY REFV3_LN_INV_MODE
#endif
static_assert(
  REFV3_LN_INV_MODE == REFV3_LN_INV_MODE_PURE_LUT ||
    REFV3_LN_INV_MODE == REFV3_LN_INV_MODE_LUT_NR1,
  "REFV3_LN_INV_MODE must be PURE_LUT(0) or LUT_NR1(1)");
static_assert(
  REFV3_LN_INV_SQRT_SYNTH_POLICY == REFV3_LN_INV_MODE,
  "REFV3_LN_INV_SQRT_SYNTH_POLICY must equal REFV3_LN_INV_MODE");

#ifndef REFV3_SOFTMAX_EXP_SYNTH_POLICY
#define REFV3_SOFTMAX_EXP_SYNTH_POLICY 0
#endif
#ifndef REFV3_SOFTMAX_EXP_SYNTH_LUT_ONLY
#define REFV3_SOFTMAX_EXP_SYNTH_LUT_ONLY 0
#endif
#ifndef REFV3_SOFTMAX_EXP_SYNTH_LERP_LUT
#define REFV3_SOFTMAX_EXP_SYNTH_LERP_LUT 1
#endif
static_assert(
  REFV3_SOFTMAX_EXP_SYNTH_POLICY == REFV3_SOFTMAX_EXP_SYNTH_LUT_ONLY ||
    REFV3_SOFTMAX_EXP_SYNTH_POLICY == REFV3_SOFTMAX_EXP_SYNTH_LERP_LUT,
  "REFV3_SOFTMAX_EXP_SYNTH_POLICY must be LUT_ONLY(0) or LERP_LUT(1)");

#ifndef REFV3_SOFTMAX_RCP_MODE_PURE_LUT
#define REFV3_SOFTMAX_RCP_MODE_PURE_LUT 0
#endif
#ifndef REFV3_SOFTMAX_RCP_MODE_LUT_NR1
#define REFV3_SOFTMAX_RCP_MODE_LUT_NR1 1
#endif

#ifndef REFV3_SOFTMAX_RCP_MODE
#ifdef REFV3_SOFTMAX_RCP_SYNTH_POLICY
#define REFV3_SOFTMAX_RCP_MODE REFV3_SOFTMAX_RCP_SYNTH_POLICY
#else
#define REFV3_SOFTMAX_RCP_MODE REFV3_SOFTMAX_RCP_MODE_PURE_LUT
#endif
#endif

#ifndef REFV3_SOFTMAX_RCP_SYNTH_LUT_ONLY
#define REFV3_SOFTMAX_RCP_SYNTH_LUT_ONLY REFV3_SOFTMAX_RCP_MODE_PURE_LUT
#endif
#ifndef REFV3_SOFTMAX_RCP_SYNTH_LUT_PLUS_NR1
#define REFV3_SOFTMAX_RCP_SYNTH_LUT_PLUS_NR1 REFV3_SOFTMAX_RCP_MODE_LUT_NR1
#endif

#ifndef REFV3_SOFTMAX_RCP_SYNTH_POLICY
#define REFV3_SOFTMAX_RCP_SYNTH_POLICY REFV3_SOFTMAX_RCP_MODE
#endif
static_assert(
  REFV3_SOFTMAX_RCP_MODE == REFV3_SOFTMAX_RCP_MODE_PURE_LUT ||
    REFV3_SOFTMAX_RCP_MODE == REFV3_SOFTMAX_RCP_MODE_LUT_NR1,
  "REFV3_SOFTMAX_RCP_MODE must be PURE_LUT(0) or LUT_NR1(1)");
static_assert(
  REFV3_SOFTMAX_RCP_SYNTH_POLICY == REFV3_SOFTMAX_RCP_MODE,
  "REFV3_SOFTMAX_RCP_SYNTH_POLICY must equal REFV3_SOFTMAX_RCP_MODE");

#ifndef REFV3_LN_BASELINE_EXTRA_NR_ITERS
#define REFV3_LN_BASELINE_EXTRA_NR_ITERS 6
#endif
static_assert(REFV3_LN_BASELINE_EXTRA_NR_ITERS >= 0,
              "REFV3_LN_BASELINE_EXTRA_NR_ITERS must be non-negative");

static_assert(REFV3_TOKENS_T > 0, "REFV3_TOKENS_T must be positive");
static_assert(REFV3_D_MODEL > 0, "REFV3_D_MODEL must be positive");
static_assert(REFV3_HEADS > 0, "REFV3_HEADS must be positive");
static_assert(REFV3_D_HEAD > 0, "REFV3_D_HEAD must be positive");
static_assert(REFV3_FF_DIM > 0, "REFV3_FF_DIM must be positive");
static_assert(REFV3_HEADS * REFV3_D_HEAD == REFV3_D_MODEL,
              "REFV3_HEADS * REFV3_D_HEAD must equal REFV3_D_MODEL");

static inline int REFV3_flatten_row_major_index(int token_row, int dim_col) {
  return (token_row * REFV3_D_MODEL) + dim_col;
}

} // namespace ref_v3
} // namespace aecct_ref
