# REF_V3 block filelist for RefV3FfnLinear0ReluBlock
AECCT_ac_ref/catapult/ref_v3/blocks/ref_v3_ffn_linear0_relu_block_top_entry.cpp
AECCT_ac_ref/src/ref_v3/RefV3FfnLinear0ReluBlock.cpp
AECCT_ac_ref/src/ref_v3/RefV3WeightsFp16LocalOnly.cpp

