#!/usr/bin/env python3
import argparse
import math
from pathlib import Path


def fmt_f32(x: float) -> str:
    return f"{x:.9e}f"


def gen_softmax_lut(path: Path, neg_t: float, exp_size: int, rcp_size: int, sumexp_max: float) -> None:
    exp_vals = []
    for i in range(exp_size):
        x = -neg_t * (float(i) / float(exp_size - 1))
        exp_vals.append(math.exp(x))

    rcp_vals = []
    for i in range(rcp_size):
        s = 1.0 + (sumexp_max - 1.0) * (float(i) / float(rcp_size - 1))
        rcp_vals.append(1.0 / s)

    lines = []
    lines.append("#ifndef AECCT_REF_SOFTMAX_APPROX_LUT_DATA_H")
    lines.append("#define AECCT_REF_SOFTMAX_APPROX_LUT_DATA_H")
    lines.append("")
    lines.append("// AUTO-GENERATED by tools/gen_ref_lut.py")
    lines.append("// Params: T=12, EXP=256, RCP=256")
    lines.append("")
    lines.append(f"static const float g_ref_softmax_exp_lut[{exp_size}] = {{")
    for i, v in enumerate(exp_vals):
        comma = "," if i != exp_size - 1 else ""
        lines.append(f"  {fmt_f32(v)}{comma}")
    lines.append("};")
    lines.append("")
    lines.append(f"static const float g_ref_softmax_rcp_lut[{rcp_size}] = {{")
    for i, v in enumerate(rcp_vals):
        comma = "," if i != rcp_size - 1 else ""
        lines.append(f"  {fmt_f32(v)}{comma}")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def gen_invsqrt_header(path: Path, lut_size: int, x_min: float, x_max: float) -> None:
    vals = []
    for i in range(lut_size):
        x = x_min + (x_max - x_min) * (float(i) / float(lut_size - 1))
        vals.append(1.0 / math.sqrt(x))

    lines = []
    lines.append("#ifndef AECCT_REF_INV_SQRT_APPROX_H")
    lines.append("#define AECCT_REF_INV_SQRT_APPROX_H")
    lines.append("")
    lines.append("#include \"ac_std_float.h\"")
    lines.append("")
    lines.append("namespace aecct_ref {")
    lines.append("")
    lines.append("typedef ac_ieee_float<binary32> ref_invsqrt_fp32_t;")
    lines.append("")
    lines.append("static const int REF_INV_SQRT_LUT_SIZE = %d;" % lut_size)
    lines.append("static const float REF_INV_SQRT_X_MIN = %s;" % fmt_f32(x_min))
    lines.append("static const float REF_INV_SQRT_X_MAX = %s;" % fmt_f32(x_max))
    lines.append("static const float REF_INV_SQRT_IDX_SCALE = %s;" % fmt_f32((lut_size - 1) / (x_max - x_min)))
    lines.append("")
    lines.append("static const float g_ref_inv_sqrt_lut[%d] = {" % lut_size)
    for i, v in enumerate(vals):
        comma = "," if i != lut_size - 1 else ""
        lines.append(f"  {fmt_f32(v)}{comma}")
    lines.append("};")
    lines.append("")
    lines.append("static inline int ref_invsqrt_idx(ref_invsqrt_fp32_t x) {")
    lines.append("  ref_invsqrt_fp32_t xf = x;")
    lines.append("  if (xf < ref_invsqrt_fp32_t(REF_INV_SQRT_X_MIN)) xf = ref_invsqrt_fp32_t(REF_INV_SQRT_X_MIN);")
    lines.append("  if (xf > ref_invsqrt_fp32_t(REF_INV_SQRT_X_MAX)) xf = ref_invsqrt_fp32_t(REF_INV_SQRT_X_MAX);")
    lines.append("  ref_invsqrt_fp32_t pos = (xf - ref_invsqrt_fp32_t(REF_INV_SQRT_X_MIN)) * ref_invsqrt_fp32_t(REF_INV_SQRT_IDX_SCALE);")
    lines.append("  int idx = (pos + ref_invsqrt_fp32_t(0.5f)).to_float();")
    lines.append("  if (idx < 0) idx = 0;")
    lines.append("  if (idx >= REF_INV_SQRT_LUT_SIZE) idx = REF_INV_SQRT_LUT_SIZE - 1;")
    lines.append("  return idx;")
    lines.append("}")
    lines.append("")
    lines.append("static inline ref_invsqrt_fp32_t ref_inv_sqrt_approx(ref_invsqrt_fp32_t x) {")
    lines.append("  ref_invsqrt_fp32_t x_safe = x;")
    lines.append("  if (x_safe < ref_invsqrt_fp32_t(REF_INV_SQRT_X_MIN)) x_safe = ref_invsqrt_fp32_t(REF_INV_SQRT_X_MIN);")
    lines.append("  if (x_safe > ref_invsqrt_fp32_t(REF_INV_SQRT_X_MAX)) x_safe = ref_invsqrt_fp32_t(REF_INV_SQRT_X_MAX);")
    lines.append("  int idx = ref_invsqrt_idx(x_safe);")
    lines.append("  ref_invsqrt_fp32_t y0 = ref_invsqrt_fp32_t(g_ref_inv_sqrt_lut[idx]);")
    lines.append("  return y0;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace aecct_ref")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate ref softmax/inv_sqrt LUT headers")
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()

    out_dir = args.repo / "AECCT_ac_ref" / "include"
    out_dir.mkdir(parents=True, exist_ok=True)

    gen_softmax_lut(
        out_dir / "SoftmaxApproxLutData.h",
        neg_t=12.0,
        exp_size=256,
        rcp_size=256,
        sumexp_max=256.0,
    )

    gen_invsqrt_header(
        out_dir / "InvSqrtApprox.h",
        lut_size=512,
        x_min=1.0e-2,
        x_max=8.0,
    )

    print("generated:")
    print(out_dir / "SoftmaxApproxLutData.h")
    print(out_dir / "InvSqrtApprox.h")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
